# 教程
https://tangshusen.me/Deep-Learning-with-PyTorch-Chinese/#/chapter2/2.1

In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8847, 0.6746, 0.4217],
        [0.1224, 0.4793, 0.6108],
        [0.2934, 0.8574, 0.5814],
        [0.1806, 0.2927, 0.9959],
        [0.7204, 0.6085, 0.0191]])


In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
a = [1.0, 2.0, 1.0]

In [4]:
a[0]

1.0

In [5]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [6]:
import torch 
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [11]:
# 使用.zeros是获取适当大小的数组的一种方法
points = torch.zeros(6)
# 用所需的值覆盖这些0
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

points


tensor([1., 4., 2., 1., 3., 5.])

In [31]:
# 相同效果
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points


tensor([1., 4., 2., 1., 3., 5.])

In [14]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [28]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [16]:
# 获取张量的形状
points.shape

torch.Size([3, 2])

In [18]:
points = torch.ones(3, 2)
points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [37]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [51]:
points[0, 1]


tensor(4.)

In [23]:
points[0]

tensor([1., 4.])

In [26]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [32]:
points_storage = points.storage()
points_storage[0]

1.0

In [33]:
points.storage()[1]

4.0

In [52]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points


tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [60]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()


2

In [54]:
second_point.size()

torch.Size([2])

In [55]:
second_point.shape

torch.Size([2])

In [56]:
points.stride()

(2, 1)

In [61]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()


torch.Size([2])

In [62]:
second_point.storage_offset()


2

In [63]:
second_point.stride()


(1,)

In [64]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points


tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [68]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone() # 克隆子张量可以避免改变张量
second_point[0] = 10.0
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [69]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [70]:
points_t = points.t() # 转置
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [71]:
id(points.storage()) == id(points_t.storage())


True

In [72]:
points.stride()


(2, 1)

In [73]:
points_t.stride()


(1, 2)

In [74]:
some_tensor = torch.ones(3, 4, 5)
some_tensor.shape, some_tensor.stride()


(torch.Size([3, 4, 5]), (20, 5, 1))

In [75]:
# 三维张量
some_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [76]:
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor_t.shape, some_tensor_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [77]:
some_tensor_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [78]:
# 转置张量不连续
points.is_contiguous(), points_t.is_contiguous()


(True, False)

In [79]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [80]:
points_t.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [81]:
points_t.stride()


(1, 2)

In [82]:
points_t_cont = points_t.contiguous() # 从非连续张量获得新的连续张量
points_t_cont


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [83]:
points_t_cont.stride()


(3, 1)

In [84]:
points_t_cont.storage()


 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [85]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)


In [86]:
short_points.dtype


torch.int16

In [87]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()


In [91]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [99]:
# randn返回一个元素是0到1之间随机数的张量。
points = torch.randn(10, 2)
short_points = points.type(torch.short)


In [102]:
points

tensor([[ 0.4400, -0.2043],
        [-0.4277,  0.4205],
        [ 0.1769,  1.2615],
        [ 0.4032,  0.5270],
        [ 0.6997,  1.6771],
        [ 0.4899,  0.6566],
        [ 0.1924,  1.1179],
        [ 1.0945, -1.8100],
        [ 1.3473, -0.9825],
        [-0.5468,  1.5770]])

In [105]:
some_list

[0, 1, 2, 3, 4, 5]

In [103]:
some_list = list(range(6))
some_list[:]     # 所有元素
some_list[1:4]   # 第1（含）到第4（不含）个元素
some_list[1:]    # 第1（含）个之后所有元素
some_list[:4]    # 第4（不含）个之前所有元素
some_list[:-1]   # 最末尾（不含）元素之前所有元素
some_list[1:4:2] # 范围1（含）到4（不含），步长为2的元素


[1, 3]

In [110]:
points

tensor([[ 0.4400, -0.2043],
        [-0.4277,  0.4205],
        [ 0.1769,  1.2615],
        [ 0.4032,  0.5270],
        [ 0.6997,  1.6771],
        [ 0.4899,  0.6566],
        [ 0.1924,  1.1179],
        [ 1.0945, -1.8100],
        [ 1.3473, -0.9825],
        [-0.5468,  1.5770]])

In [115]:
#points[1:]    # 第1行及之后所有行，（默认）所有列
#points[1:, :] # 第1行及之后所有行，所有列
points[1:, 0] # 第1行及之后所有行，仅第0列


tensor([-0.4277,  0.1769,  0.4032,  0.6997,  0.4899,  0.1924,  1.0945,  1.3473,
        -0.5468])

In [116]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np
# 修改得到的NumPy数组会导致原始张量发生变化。

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [117]:
points = torch.from_numpy(points_np)