# 教程
https://tangshusen.me/Deep-Learning-with-PyTorch-Chinese/#/chapter2/2.1

In [78]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7203, 0.4110, 0.7731],
        [0.2695, 0.8498, 0.5483],
        [0.5943, 0.4874, 0.8525],
        [0.5626, 0.0412, 0.2542],
        [0.1665, 0.2264, 0.2125]])


In [79]:
import torch
torch.cuda.is_available()

True

In [80]:
a = [1.0, 2.0, 1.0]

In [81]:
a[0]

1.0

In [82]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [83]:
import torch 
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [84]:
a[1]

tensor(1.)

In [85]:
float(a[1])

1.0

In [86]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [87]:
# 使用.zeros是获取适当大小的数组的一种方法
points = torch.zeros(6)
# 用所需的值覆盖这些0
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

points


tensor([1., 4., 2., 1., 3., 5.])

In [88]:
# 相同效果
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points


tensor([1., 4., 2., 1., 3., 5.])

In [89]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [90]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [91]:
# 获取张量的形状
points.shape

torch.Size([3, 2])

In [92]:
points = torch.ones(3, 2)
points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [93]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [94]:
points[0, 1]


tensor(4.)

In [95]:
points[0]

tensor([1., 4.])

In [96]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [97]:
points_storage = points.storage()
points_storage[0]

1.0

In [98]:
points.storage()[1]

4.0

In [99]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points


tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [100]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()


2

In [101]:
second_point.size()

torch.Size([2])

In [102]:
second_point.shape

torch.Size([2])

In [103]:
points.stride()

(2, 1)

In [104]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()


torch.Size([2])

In [105]:
second_point.storage_offset()


2

In [106]:
second_point.stride()


(1,)

In [107]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points


tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [108]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone() # 克隆子张量可以避免改变张量
second_point[0] = 10.0
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [109]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [110]:
points_t = points.t() # 转置
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [111]:
id(points.storage()) == id(points_t.storage())


True

In [112]:
points.stride()


(2, 1)

In [113]:
points_t.stride()


(1, 2)

In [114]:
some_tensor = torch.ones(3, 4, 5)
some_tensor.shape, some_tensor.stride()


(torch.Size([3, 4, 5]), (20, 5, 1))

In [115]:
# 三维张量
some_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [116]:
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor_t.shape, some_tensor_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [117]:
some_tensor_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [118]:
# 转置张量不连续
points.is_contiguous(), points_t.is_contiguous()


(True, False)

In [119]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [120]:
points_t.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [121]:
points_t.stride()


(1, 2)

In [122]:
points_t_cont = points_t.contiguous() # 从非连续张量获得新的连续张量
points_t_cont


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [123]:
points_t_cont.stride()


(3, 1)

In [124]:
points_t_cont.storage()


 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [125]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)


In [126]:
short_points.dtype


torch.int16

In [127]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()


In [128]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [129]:
# randn返回一个元素是0到1之间随机数的张量。
points = torch.randn(10, 2)
short_points = points.type(torch.short)


In [130]:
points

tensor([[ 0.6581,  0.4857],
        [ 0.7902, -0.6545],
        [-1.7981, -0.4277],
        [ 0.5764, -0.8421],
        [-1.8197,  0.7315],
        [-1.7904, -1.9903],
        [ 0.5159, -2.0288],
        [ 0.9047, -1.5829],
        [ 0.0069,  0.7127],
        [-0.5085,  1.0699]])

In [131]:
some_list = list(range(6))
some_list[:]     # 所有元素
some_list[1:4]   # 第1（含）到第4（不含）个元素
some_list[1:]    # 第1（含）个之后所有元素
some_list[:4]    # 第4（不含）个之前所有元素
some_list[:-1]   # 最末尾（不含）元素之前所有元素
some_list[1:4:2] # 范围1（含）到4（不含），步长为2的元素


[1, 3]

In [132]:
some_list

[0, 1, 2, 3, 4, 5]

In [133]:
points

tensor([[ 0.6581,  0.4857],
        [ 0.7902, -0.6545],
        [-1.7981, -0.4277],
        [ 0.5764, -0.8421],
        [-1.8197,  0.7315],
        [-1.7904, -1.9903],
        [ 0.5159, -2.0288],
        [ 0.9047, -1.5829],
        [ 0.0069,  0.7127],
        [-0.5085,  1.0699]])

In [134]:
#points[1:]    # 第1行及之后所有行，（默认）所有列
#points[1:, :] # 第1行及之后所有行，所有列
points[1:, 0] # 第1行及之后所有行，仅第0列


tensor([ 0.7902, -1.7981,  0.5764, -1.8197, -1.7904,  0.5159,  0.9047,  0.0069,
        -0.5085])

In [135]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np
# 修改得到的NumPy数组会导致原始张量发生变化。

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [136]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [137]:
torch.save(points, './ourpoints.t')
# 序列化张量

In [138]:
with open('./ourpoints.t','wb') as f:
    torch.save(points, f)


In [139]:
points = torch.load('./ourpoints.t')

In [140]:
with open('./ourpoints.t','rb') as f:
    points = torch.load(f)


In [141]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')

In [142]:
# 将cpu上的张量复制到gpu上
points_gpu = points.to(device='cuda')

In [143]:
# 多个gpu,指定gpu
points_gpu = points.to(device='cuda:0')

In [144]:
points = 2 * points # cpu
points_gpu = 2 * points.to(device='cuda') #gpu

In [145]:
points_gpu = points_gpu + 4

In [146]:
points_cpu = points_gpu.to(device='cpu')

In [147]:
# 速记
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [148]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [149]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [150]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

# 时间序列

In [151]:
import numpy as np
bikes_numpy = np.loadtxt("./dateset/hour-fixed.csv",
    dtype=np.float32,
    delimiter=",",
    skiprows=1,
    converters={1: lambda x: float(x[8:10])}
)
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

instant      # index of record #索引记录  
day          # day of month #一个月中的某天  
season       # season (1: spring, 2: summer, 3: fall, 4: winter) #季节（1：春天，2：夏天，3：秋天，4：冬天）  
yr           # year (0: 2011, 1: 2012) #年份  
mnth         # month (1 to 12) #月  
hr           # hour (0 to 23) #小时  
holiday      # holiday status #假期状态  
weekday      # day of the week #一周的某天  
workingday   # working day status #工作状态  
weathersit   # weather situation #天气情况               
                         # (1: clear, 2:mist, 3: light rain/snow, 4: heavy rain/snow) #1：晴，2：薄雾，3：小雨/雪，4：大雨/雪  
temp         # temperature in C #摄氏温度  
atemp        # perceived temperature in C #感知温度（摄氏度）  
hum          # humidity #湿度  
windspeed    # windspeed #风速  
casual       # number of causal users #因果用户数  
registered   # number of registered users #注册用户数  
cnt          # count of rental bikes #出租自行车数  

In [152]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [153]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1]) # -1将数据变回一维
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [154]:
daily_bikes = daily_bikes.transpose(1, 2) 
daily_bikes.shape, daily_bikes.stride()


(torch.Size([730, 17, 24]), (408, 1, 17))

In [155]:
first_day = bikes[:24].long() 
weather_onehot = torch.zeros(first_day.shape[0], 4) 
first_day[:,9]


tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [156]:
# 一天中的数据
weather_onehot.scatter_(
  dim=1,
  index=first_day[:,9].unsqueeze(1) - 1,
  value=1.0)


tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [157]:
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,  6.0000,
          0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,  3.0000, 13.0000,
         16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [158]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
daily_bikes.shape[2]) 
daily_weather_onehot.shape


torch.Size([730, 4, 24])

In [159]:
daily_weather_onehot.scatter_(1, daily_bikes[:,9,:].long().unsqueeze(1) - 1,
                                                            1.0) 
daily_weather_onehot.shape


torch.Size([730, 4, 24])

In [160]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)


In [161]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0


In [162]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = (daily_bikes[:, 10, :] - temp_min) / (temp_max -
     temp_min)


In [163]:
temp = daily_bikes[:, 10, :] 
daily_bikes[:, 10, :] = (daily_bikes[:, 10, :] - torch.mean(temp)) / torch.std(temp)


# 图像数据

In [165]:
import imageio
img_arr = imageio.imread(r'./dateset/bobby.jpg') 
img_arr.shape


(720, 1280, 3)