# 教程
https://tangshusen.me/Deep-Learning-with-PyTorch-Chinese/#/chapter2/2.1

In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.0347, 0.9349, 0.9840],
        [0.9395, 0.3387, 0.8009],
        [0.1594, 0.6803, 0.3665],
        [0.0151, 0.4355, 0.8862],
        [0.5963, 0.1563, 0.0676]])


In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
a = [1.0, 2.0, 1.0]

In [4]:
a[0]

1.0

In [5]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [6]:
import torch 
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
# 使用.zeros是获取适当大小的数组的一种方法
points = torch.zeros(6)
# 用所需的值覆盖这些0
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

points


tensor([1., 4., 2., 1., 3., 5.])

In [11]:
# 相同效果
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points


tensor([1., 4., 2., 1., 3., 5.])

In [12]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [13]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [14]:
# 获取张量的形状
points.shape

torch.Size([3, 2])

In [15]:
points = torch.ones(3, 2)
points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [16]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [17]:
points[0, 1]


tensor(4.)

In [18]:
points[0]

tensor([1., 4.])

In [19]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [20]:
points_storage = points.storage()
points_storage[0]

1.0

In [21]:
points.storage()[1]

4.0

In [22]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points


tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [23]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()


2

In [24]:
second_point.size()

torch.Size([2])

In [25]:
second_point.shape

torch.Size([2])

In [26]:
points.stride()

(2, 1)

In [27]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()


torch.Size([2])

In [28]:
second_point.storage_offset()


2

In [29]:
second_point.stride()


(1,)

In [30]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points


tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [31]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone() # 克隆子张量可以避免改变张量
second_point[0] = 10.0
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [32]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points


tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [33]:
points_t = points.t() # 转置
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [34]:
id(points.storage()) == id(points_t.storage())


True

In [35]:
points.stride()


(2, 1)

In [36]:
points_t.stride()


(1, 2)

In [37]:
some_tensor = torch.ones(3, 4, 5)
some_tensor.shape, some_tensor.stride()


(torch.Size([3, 4, 5]), (20, 5, 1))

In [38]:
# 三维张量
some_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [39]:
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor_t.shape, some_tensor_t.stride()


(torch.Size([5, 4, 3]), (1, 5, 20))

In [40]:
some_tensor_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [41]:
# 转置张量不连续
points.is_contiguous(), points_t.is_contiguous()


(True, False)

In [42]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [43]:
points_t.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [44]:
points_t.stride()


(1, 2)

In [45]:
points_t_cont = points_t.contiguous() # 从非连续张量获得新的连续张量
points_t_cont


tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [46]:
points_t_cont.stride()


(3, 1)

In [47]:
points_t_cont.storage()


 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)


In [49]:
short_points.dtype


torch.int16

In [50]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()


In [51]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [52]:
# randn返回一个元素是0到1之间随机数的张量。
points = torch.randn(10, 2)
short_points = points.type(torch.short)


In [53]:
points

tensor([[-0.6116, -0.1448],
        [-2.0839,  0.1951],
        [ 0.1216, -0.6876],
        [-0.8279,  0.9973],
        [-0.6546, -0.6354],
        [ 1.5567,  2.4612],
        [-0.9895, -1.1503],
        [-0.4299, -0.6353],
        [ 0.9628, -0.2504],
        [ 0.7775, -0.5126]])

In [103]:
some_list = list(range(6))
some_list[:]     # 所有元素
some_list[1:4]   # 第1（含）到第4（不含）个元素
some_list[1:]    # 第1（含）个之后所有元素
some_list[:4]    # 第4（不含）个之前所有元素
some_list[:-1]   # 最末尾（不含）元素之前所有元素
some_list[1:4:2] # 范围1（含）到4（不含），步长为2的元素


[1, 3]

In [54]:
some_list

NameError: name 'some_list' is not defined

In [110]:
points

tensor([[ 0.4400, -0.2043],
        [-0.4277,  0.4205],
        [ 0.1769,  1.2615],
        [ 0.4032,  0.5270],
        [ 0.6997,  1.6771],
        [ 0.4899,  0.6566],
        [ 0.1924,  1.1179],
        [ 1.0945, -1.8100],
        [ 1.3473, -0.9825],
        [-0.5468,  1.5770]])

In [115]:
#points[1:]    # 第1行及之后所有行，（默认）所有列
#points[1:, :] # 第1行及之后所有行，所有列
points[1:, 0] # 第1行及之后所有行，仅第0列


tensor([-0.4277,  0.1769,  0.4032,  0.6997,  0.4899,  0.1924,  1.0945,  1.3473,
        -0.5468])

In [116]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np
# 修改得到的NumPy数组会导致原始张量发生变化。

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [119]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [120]:
torch.save(points, './ourpoints.t')
# 序列化张量

In [121]:
with open('./ourpoints.t','wb') as f:
    torch.save(points, f)


In [124]:
points = torch.load('./ourpoints.t')

In [126]:
with open('./ourpoints.t','rb') as f:
    points = torch.load(f)


In [55]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')

In [56]:
# 将cpu上的张量复制到gpu上
points_gpu = points.to(device='cuda')

In [57]:
# 多个gpu,指定gpu
points_gpu = points.to(device='cuda:0')

In [58]:
points = 2 * points # cpu
points_gpu = 2 * points.to(device='cuda') #gpu

In [59]:
points_gpu = points_gpu + 4

In [60]:
points_cpu = points_gpu.to(device='cpu')

In [61]:
# 速记
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [56]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [58]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [59]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])